name: Push

on:
  - push
jobs:

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: load client
        run: |
          .github/helpers/build.sh b2b ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: check access to client
        run: |
          cd client
          ls -la
        shell: bash


          
