name: Push

on:
  push:
    branches:
      - env/qa
      - env/dev

env:
  RPM_ENVIRONMENT: b2b-qa
  REACT_APP_RPM_ENVIRONMENT: b2b-qa

jobs:
  package-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # check which github branch is being pushed to
      - uses: actions/checkout@v3
      - name: Set env
        run: |
            echo BALANCE_ENVIRONMENT=b2b-$(basename $GITHUB_REF) >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_REF
        shell: bash



          
