name: Push

on:
  push:
    branches:
      - env/*


jobs:
  set-rpm-environment:
    
  deploy-dev:
    if: github.ref == 'refs/heads/env/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: load client
        run: |
          .github/helpers/build.sh b2b ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: check access to client
        run: |
          cd client
          ls -la
        shell: bash

      - name: dev deployed
        run: |
          echo The PR was deployed
        shell: bash

  deploy-uat:
    if: github.ref == 'refs/heads/env/uat'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: load client
        run: |
          .github/helpers/build.sh b2b ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: check access to client
        run: |
          cd client
          ls -la
        shell: bash

      - name: uat deployed
        run: |
          echo The PR was deployed
        shell: bash




          
