name: Push

on:
  push:
    branches:
      - env/qa

env:
  RPM_ENVIRONMENT: b2b-qa
  REACT_APP_RPM_ENVIRONMENT: b2b-qa

jobs:
  package-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: load client
        run: |
          .github/helpers/build.sh b2b ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: check access to client
        run: |
          cd client
          ls -la
        shell: bash

      - name: dev deployed
        run: |
          echo $REACT_APP_RPM_ENVIRONMENT
          echo dev-${GITHUB_SHA::8}-$(date +%s)
        shell: bash



          
