name: Push

on:
  push:
    branches:
      - env/qa
      - env/dev

env:
  RPM_ENVIRONMENT: b2b-qa
  REACT_APP_RPM_ENVIRONMENT: b2b-qa

jobs:
  package-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # check which github branch is being pushed to
      - uses: actions/checkout@v3
      - name: Set env
        run: |
          echo "Checking out branch: $GITHUB_REF"

          if [ "$GITHUB_REF" == "refs/heads/env/qa" ]; then
            "BALANCE_ENVIRONMENT=echo qa" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" == "refs/heads/env/dev" ]; then
            "BALANCE_ENVIRONMENT=echo dev" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" == "refs/heads/env/uat" ]; then
            "BALANCE_ENVIRONMENT=echo uat" >> $GITHUB_ENV
          else
            exit 1
          fi
      - name: Test
        run: echo $BALANCE_ENVIRONMENT
        shell: bash



          
