name: Push

on:
  push:
    branches:
      - env/qa

env:
  DAY_OF_WEEK: Monday

jobs:
  package-frontend:
    env:
      RPM_ENVIRONMENT: b2b-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: load client
        run: |
          .github/helpers/build.sh b2b ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: check access to client
        run: |
          cd client
          ls -la
        shell: bash

      - name: dev deployed
        run: |
          echo $REACT_APP_RPM_ENVIRONMENT
        shell: bash



          
