name: Push

on:
  pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  package-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: load client
        run: |
          .github/helpers/build.sh b2b ${{ secrets.PAT_TOKEN }}
        shell: bash